receivers:
  filelog:
    include:
      - /hostfs/var/log/myapp/app.log
    include_file_path: true
    force_flush_period: 0 

exporters:
  coralogix:
    domain: "YOURDOMAIN"
    private_key: "YOURKEY"
    application_name: "logtest"
    subsystem_name: "logtest"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: [ filelog ]
      exporters: [ coralogix ]
